"<Object defined dielectric>"
"5CB - Li"
"5PCH - Li"
"6241-000 - Li"
"Ag (Silver) - CRC"
"Ag (Silver) - Johnson and Christy"
"Ag (Silver) - Palik (0-2um)"
"Ag (Silver) - Palik (1-10um)"
"Al (Aluminium) - CRC"
"Al (Aluminium) - Palik"
"Al2O3 - Palik"
"Au (Gold) - CRC"
"Au (Gold) - Johnson and Christy"
"Au (Gold) - Palik"
"C (graphene) - Falkovsky (mid-IR)"
"Cr (Chromium) - CRC"
"Cr (Chromium) - Palik"
"Cu (Copper) - CRC"
"Cu (Copper) - Palik"
"E44 - Li"
"E7 - Li"
"Fe (Iron) - CRC"
"Fe (Iron) - Palik"
"GaAs - Palik"
"Ge (Germanium) - CRC"
"Ge (Germanium) - Palik"
"H2O (Water) - Palik"
"In (Indium) - Palik"
"InAs - Palik"
"InP - Palik"
"MLC-6608 - Li"
"MLC-9200-000 - Li"
"MLC-9200-100 - Li"
"Ni (Nickel) - CRC"
"Ni (Nickel) - Palik"
"PEC (Perfect Electrical Conductor)"
"Pd (Palladium) - Palik"
"Pt (Platinum) - Palik"
"Rh (Rhodium) - Palik"
"Si (Silicon) - Palik"
"Si3N4 (Silicon Nitride) - Kischkat"
"Si3N4 (Silicon Nitride) - Luke"
"Si3N4 (Silicon Nitride) - Phillip"
"SiO2 (Glass) - Palik"
"Sn (Tin) - Palik"
"TL-216 - Li"
"Ta (Tantalum) - CRC"
"Ti (Titanium) - CRC"
"Ti (Titanium) - Palik"
"TiN - Palik"
"TiO2 (Titanium Dioxide) - Devore"
"TiO2 (Titanium Dioxide) - Kischkat"
"TiO2 (Titanium Dioxide) - Sarkar"
"TiO2 (Titanium Dioxide) - Siefke"
"V (Vanadium ) - CRC"
"W (Tungsten) - CRC"
"W (Tungsten) - Palik"
"etch"